### ISSUE TITLE
M2: Production-ready Airflow integration

### ISSUE THREAD

**Issue by aronchick** [bacalhau-project/bacalhau#1176]
ETA: 2023Q1

Parent milestone: https://github.com/filecoin-project/bacalhau/issues/1183

## TODO from [M1 parent milestone](https://github.com/filecoin-project/bacalhau/issues/1183):

- [x] https://github.com/filecoin-project/bacalhau/issues/1564
- [x] ~https://github.com/filecoin-project/bacalhau/issues/1555~
- [x] https://github.com/filecoin-project/bacalhau/issues/1581
- [x] ~https://github.com/filecoin-project/bacalhau/issues/1483~

## M2 items:

- [x] https://github.com/filecoin-project/bacalhau/issues/1155
- [x] https://github.com/filecoin-project/bacalhau/issues/1484
  - [x] https://github.com/filecoin-project/bacalhau/pull/1924 (first iteration)
  - [x] more iterations to come...
- [x] ~#1177~
- [ ] #1178

### Lineage:
- [x] https://github.com/filecoin-project/bacalhau/issues/1479 (thanks to Polyphene.io [grant programme])
- [x] OpenLineage PoC https://github.com/enricorotundo/bacalhau-airflow-provider/pull/1 (thanks to Polyphene.io [grant programme])
- [x] https://github.com/filecoin-project/bacalhau/issues/1503 (thanks to Polyphene.io [grant programme to PoC this out])
- [x] https://github.com/filecoin-project/bacalhau/issues/1235

### Host airflow:
- [x] ~Go through networking doc and related [PR](https://github.com/filecoin-project/bacalhau/pull/1571)~
- [x] ~https://github.com/filecoin-project/bacalhau/issues/1480~
- [x] ~https://github.com/filecoin-project/bacalhau/issues/1246~

**Comment by aronchick** [comment]
Enrico - please fill out the best you can
