### ISSUE TITLE
Long Running Jobs v1

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#2502]
Allows users to run jobs that persist over time, responding to new input as it arrives. If a node goes down, the job is restarted when it comes back up.

### Unlocked user value:
- Applying new input that arrives over time against a machine-learning model, on the order of milliseconds per input (Mycelial)
- Running a job that reads from logs as they are populated, transforming each input and storing it in some location
- Running a “hot container” that has done an amount of intensive setup and can now quickly generate results (e.g. setting up Stable Diffusion)

### Backlog:
1. Talk to Mycelial and write up their requirements – consider input data rate
2. Review the modular architecture doc and work out an MVP for an API server and first module to handle streaming jobs
3. …

### It’s done when:
- Code: working example/case study merged using main release
- Docs: how to run one, what the interface is within a job (if any)
- Media: video demo on the website alongside case study

### People:
- Pilot: @wdbaruni 
- Co-pilot: @frrist 

### Sub-Tasks:
- #2503
- #2504

[Reference](https://www.notion.so/Feature-Roadmap-Mission-and-Goals-ee6d15c1a9d54e1fbb6fa3288f34a53a?pvs=4#a993a677efd44c21aa626b2d448dfeee)
```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2503
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2504
- [ ] https://github.com/bacalhau-project/bacalhau/pull/2600
- [ ] https://github.com/bacalhau-project/bacalhau/pull/2616
```

**Comment by aronchick** [comment]
Done?

**Comment by frrist** [comment]
Will default to @wdbaruni on this. I believe the work is complete.
