### ISSUE TITLE
Job queuing and persistence v1

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#2580]
Allows users to submit jobs beyond network capacity and have Bacalhau orchestrate them in some order as network capacity becomes available. If the requester node restarts, it remembers the jobs in the queue and any long-running jobs it is responsible for.

## Unlocked user value:

- Reliable job scheduling – users can now “fire and forget” a job and know that Bacalhau will deliver the results eventually
- Load spike handling – users can now submit 000’s of jobs at once and rely on Bacalhau to orchestrate them reliably (e.g. Amplify)
- Streaming jobs across restarts – users can specify a long-running job and be confident the job is restarted automatically when the node restarts

Backlog:

1. Talk to users and write up their requirements – consider how their jobs will be orchestrated now and in v2
2. Talk to users and write up why how they’re using Bacalhau generates 000’s of jobs
3. Review the existing storage interfaces (LocalDB, JobStore, ExecutionStore, DashboardDB) and come up with a plan for unifying these into an object store (#1943)
4. Design feature(s) as necessary
5. …

It’s done when:

- Code: features live on prod!
- Docs: soft limits, hard limits and how to configure them
- Media: video demo of 000’s of jobs submitted at once

People:

- Pilot: @rossjones 
- Co-pilot: @wdbaruni 
```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2630
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2631
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2645
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2632
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2658
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2659
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2657
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2716
```
