### ISSUE TITLE
Jobs on Private Data

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2742]
Allow jobs to run against data that should be kept private from other users. This should cover job level private data, node level private data, encrypted comms with bacalhau APIs. 

## User value 

* Users at different trust levels: having a broad set of users able to access a Bacalhau network with not all of the data that is available to the network being usable by all users
* Cyber defence in depth: not assuming that users with access to the network are trusted (see [Zero Trust Architectures](https://www.gsa.gov/technology/it-contract-vehicles-and-purchasing-programs/technology-products-services/it-security/executive-order-14028)
* Secure access to organisational secrets 

## Possible approach 

* Encryption of job data: allow users to submit jobs that contain private access keys and/or API keys, and ensure that these keys aren’t visible to other users
* Vaults/ACLs: allow jobs from authenticated users to access keys or datasets stored in some secret repository. Nothing needs to be contained in the job data for this – the users’ identity is just used to unlock access to the data and/or secrets.
* Namespaces: users can no longer see each other’s jobs; each user has a private namespace for their jobs which are only accessible to them. Within a namespace no encryption of job data is necessary.

## Done when 

* Code: features to run a job over private data are released
* Docs: docs explain how to configure and use private data features
* Media: example and video of using private data
```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2743
- [ ] Node level secrets/vaults
- [ ] Investigate possible designs for namespaces (both individual and group)
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2277
```

**Comment by wdbaruni** [comment]
replaced by linear project

**Comment by cdpb** [comment]
Hey @wdbaruni, can you elaborate which linear project you're referring to?

I found a number of vault or private data issues, but non seems to really state the current state of the "compute over private data" epos.

This feature would be really helpful :)
