### ISSUE TITLE
Requester node TLS support

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#2743]
Enable the requester node to serve endpoints over TLS. This should work for clients on both public and private networks. 

```[tasklist]
### Tasks
- [x] Requester node should support --tlscert and --tlskey to for TLS config
- [x] Requester node should support --autotls to use ACME for certs.
- [x] Update client to support TLS (with optional --cacert)
- [x] Client should support --insecure for self-signed server certs
- [ ] Document usage in server (and client)
- [ ] Fix developer experience
```

**Comment by rossjones** [comment]
This was done in separate PRs and documented at https://docs.bacalhau.org/running-node/configuring-tls
