### ISSUE TITLE
Return better errors

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3791]
[Improve Error Reporting](https://github.com/bacalhau-project/expanso-planning/issues/390) and https://github.com/bacalhau-project/bacalhau/pull/3771 has created a better framework to report and display errors to the users by providing more structured errors, and reduce the need to keep on wrapping errors unnecessarily. 

What is left is to improve the coverage of different components (executors, publishers, inputs) and provide meaningful errors using the new structure

```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2397
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3059
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3813
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4032
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4171
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4234
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4228
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3893
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4345
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4346
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4404
```
