### ISSUE TITLE
Dashboard UI Q3/Q4

### ISSUE THREAD

**Issue by XandraMcC** [bacalhau-project/bacalhau#3812]
```[tasklist]
### Phase 0
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/18
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/16
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/15
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/17
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/42
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/44
```

```[tasklist]
### Phase 1
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/47
- [x] https://github.com/bacalhau-project/expanso-planning/issues/43
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/48
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/49
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/56
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/57
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/85
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/50
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/105
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/59
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/60
```

```[tasklist]
### Phase 2
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3940
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/168
- [ ] https://github.com/bacalhau-project/issue-migration/issues/134
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/52
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/65
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/66
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3937
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/54
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/67
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3933
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/69
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/78
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3925
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/80
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3923
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3900
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3895
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/184
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3935
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3891
```

```[tasklist]
### Phase 3
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3931
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/73
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3929
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/75
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3927
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/70
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/133
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/63
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3204
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3239
```

```[tasklist]
### Phase 1.1
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/64
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3915
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/135
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/136
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/137
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/138
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/139
```
