### ISSUE TITLE
Update test suites to use new CLIs and APIs

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3832]
All our test suites are using legacy `/pkg/model` package and legacy APIs to submit jobs. We should switch to using new APIs and V2 client
```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4140
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4141
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4142
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4143
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4144
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4145
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4159
```

**Comment by frrist** [comment]
being addressed at an individual CLI level via https://github.com/bacalhau-project/bacalhau/issues/3838

**Comment by frrist** [comment]
This issue also includes the devstack, and anything else that is using the old API methods. When this issue closes we must be able to delete the model and v1 api packages.
