### ISSUE TITLE
Deprecate Legacy APIs and CLIs

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3838]
The goal of this epic is to deprecate legacy `pkg/model` package, along with legacy CLIs (e.g. `bacalhau list`) and APIs (e.g. `/api/v1/requester/...`) in favour of newer CLIs (e.g. `bacalhau job list`) and APIs (e.g. `/api/v1/orchestrator/...`)

```[tasklist]
### CLI & API Migration
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3837
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4021
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4043
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4042
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4044
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4046
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4045
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4048
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3971
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4047
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4058
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4070
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3832
```
When the above list is complete we will be able to completely remove the V1 Client, API, and the `model` package. When those pieces of code are removed this issue is considered complete.

```[tasklist]
### Misc
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3839
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3863
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3719
```

**Comment by frrist** [comment]
Final PR that completes this work was merged via https://github.com/bacalhau-project/bacalhau/pull/4156
