### ISSUE TITLE
Auto-generate TLS certificates on requester node boot

### ISSUE THREAD

**Issue by simonwo** [bacalhau-project/bacalhau#3844]
```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/551
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3830
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3829
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3828
```

**Comment by wdbaruni** [comment]
@frrist what are your thoughts on this? and if we are not moving forward with this, is there any code cleanup to do?

**Comment by frrist** [comment]
The theme here seems to be "almost secure by default" which I'd argue is worse than insecure by default.
- Wearing my developer hat #3830 seems like a bad idea, I rather work with HTTP when developing.
- #3829 + #3828 also seem undesirable

I would be in favor of closing this and providing our users with documentation that describes best practices for securing a cluster.

I am not sure what PR closed https://github.com/bacalhau-project/expanso-planning/issues/551 but I think we will want some type of default key generation for securing communication over NATS.

My general feedback would be to close this issue as "Not Planned"
