### ISSUE TITLE
Job Progress Visibility

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3868]
### The Problem

Today `bacalhau docker run` and `bacalhau job run` have very limited visibility of the job’s progress, node selection, possible retries and where things might be failing. A big part for that is because the commands are relying on job and execution state to print the progress, instead of the job history events which were recently enriched with more details and hints https://github.com/bacalhau-project/bacalhau/pull/3771

### The Proposal

The proposal is to use job level and execution level history events to display the progress. There are some missing features needed today to achieve this, including:

1. Implement pagination for querying job history
2. Figure out a nice way to display these events on the console. Maybe group events by execution and only display the latest event for each execution. 
3. In the future we can implement this using websockets when we have better datastore event watcher logic that is not only limited to live events.

### Priority
- Priority: 1 (Hight)
- Quarter: 2024/Q1
- Justification:
  - Painful user experience while working on the use cases to understand why jobs are failing or not being scheduled. 
```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4177
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4220
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4233
```

**Comment by wdbaruni** [comment]
@udsamani I've updated the issue description and changed the proposal to use job history instead of evaluations
