### ISSUE TITLE
Epic: Client & Server Auto-Update and Notifications

### ISSUE THREAD

**Issue by frrist** [bacalhau-project/bacalhau#3878]
# Description

There are several scenarios here, expressed in the following table: 

|  | Client Behind Serve | Server Behind Client | Both Behind Endpoint |
|----|---------------------------|------------------------------|------------------------------|
| Client Behavior | Notify (only) user of need for client update | Notify (only) user of need for server update; Allow skew via flag | Notify (only) user of need for client update; Notify (only) user of need for server update; “Turn off all notifications on server and all clients that contact me” |
| Server Behavior | Notify (only) user of update on contact; Allow skew via flag (server or client) | Notify (only) user of need for server update; Notify SRE of skew in logs; Allow auto-update | Notify (only) user of need for server update; Notify SRE of skew in logs; Allow auto-update |

# Acceptance Criteria

```[tasklist]
### Acceptance Criteria
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/237
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/236
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/238
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/239
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/240
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/241
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/242
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3877
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3876
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3875
```

<details>
<summary>Initial Draft</summary>

At present users are presented with a text prompt in the CLI when the version of bacalhau installed on their machine does not match the version metadata hosted on http://update.bacalhau.org/version. The prompt directs users to manually run `curl -sL 'https://get.bacalhau.org/install.sh?dl=fac3c600-9660-5928-8b9b-8437f13bf9d0' | bash` on their machine in-order to update bacalhau, this is a manual process.

The current flow presents several challenges to users deploying bacalhau through a cloud marketplace:
- The version of bacalhau described at http://update.bacalhau.org/version will become out of date with the users deployed version on the marketplace. Their client will then receive the aforementioned update message. (they shouldn't follow this prompt because:)
- If users update the version of bacalhau they are using locally and do not update the version of bacalhau deployed to the marketplace their client will fail to communicate with their hosted marketplace version due to version mismatch.
- To update the version of bacalhau deployed from the marketplace users must ssh to each node, manually update the version and restart the service. This will not scale for users with many nodes.

I believe there are several ways to address the challenge presented with the current work-flow:
1. Associate the client version with the version deployed in the marketplace for each user: Instead of a client polling `update.bacalhau.org/version` for version metadata it polls a URL specific to the marketplace deployment for update status.
2. Implement auto update functionality for bacalhau deployments via tools like https://github.com/minio/selfupdate or https://github.com/sanbornm/go-selfupdate. Users could trigger a fleet-wide update via an API command
3. Permit clients to operate with servers whose versions differ from their server.  Related: https://github.com/bacalhau-project/bacalhau/issues/3163
</details>

**Comment by wdbaruni** [comment]
@coderabbitai close this issue and open a new one for self-update feature
