### ISSUE TITLE
Custom Job Types

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3902]
The aim of this work is to allow users to submit a job that is not targeted at the execution environment, but rather at the tool they wish to use.  For example, `bacalhau exec python` or `bacalhau exec duckdb` or `bacalhau exec whisper`.

Each of the previous commands would be their own job type, with their own command line parameters, and executed without the user needing to know which environment, and without the user needing to construct a docker image.  This might be considered analogous with heroku’s build-packs where Heroku was able to run your code without you knowing how.

https://www.notion.so/expanso/Custom-Job-Type-Implementation-c5064153428e41e689c2233055cadbb4
```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/159
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/160
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/161
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/162
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3901
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/164
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/185
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/186
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3892
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/195
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/203
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/204
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/247
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3874
```
