### ISSUE TITLE
API improvements and fixes

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#3943]
This epic holds set of identified issues and improvements required for our current APIs. 

We don’t need to address all these issues together as API improvement is an ongoing task, but we expect more changes and bugs given the recent API changes, new job types, and the web UI. It might be helpful to track all these issues under one place.

```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/358
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/359
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3941
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/432
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/433
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3852
```
