### ISSUE TITLE
Pluggable Executors - Phase II

### ISSUE THREAD

**Issue by rossjones** [bacalhau-project/bacalhau#3949]
Edit: We are now retargetting this work to https://www.notion.so/expanso/Executors-a3c19862cf3b496589e7537cb2200e94 - a lot of the tickets are still valid, but with different content.

We currently have two pluggable executors that can run as separate processes (docker and wasm), and can also run embedded in the main process.  Whilst we do have the pluggable executors and they can be configured to run separately, there is further work required to iterate on them. This work will enable future external plugins, and it will be required to enable the Python executor.  

```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/118
- [ ] https://github.com/bacalhau-project/expanso-planning/issues/132
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3947
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3913
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3908
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3909
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3921
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3916
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3920
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3919
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3918
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3917
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3907
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3906
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3912
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3911
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3910
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3905
```

**Comment by wdbaruni** [comment]
deprioritizing all work related to pluggable executors for now
