### ISSUE TITLE
Improved Configuration Management

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4014]
Implement bacalhau configuration improvements as suggested in https://www.notion.so/expanso/Rethinking-Configuration-435fbe87419148b4bbc5119d413786eb

```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4217
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4218
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4219
- [ ] bacalhau-project/bacalhau#3848
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4323
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4324
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4336
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4337
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4338
```
