### ISSUE TITLE
Job store performance

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4173]
Improve job store performance, specifically around listing jobs and implementing a better indexing logic for label selectors

```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4174
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4175
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3571
```

**Comment by wdbaruni** [comment]
replaced by a linear project
