### ISSUE TITLE
Redesigned Python SDK

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4178]
The goal is to redesign the Python SDK to make it more configurable and easier to use. The new SDK will harness all the features and capabilities of Bacalhau networks, providing a seamless experience for developers. Enhanced configurability will simplify integration with Bacalhau, enabling users to leverage the full power of distributed compute directly from their Python applications.

```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3218
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3223
- [ ] https://github.com/bacalhau-project/bacalhau/issues/3222
- [ ] https://github.com/bacalhau-project/bacalhau/issues/2987
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4162
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4200
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4239
```

**Comment by wdbaruni** [comment]
replaced by a linear project
