### ISSUE TITLE
Usage telemetry tracking

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4316]
To enhance the quality of Bacalhau and gain insights into network usage, we need to implement a telemetry system. This will help us prioritize features and bug fixes based on actual usage data. Our approach will focus on collecting non-personally identifiable information (non-PII) while respecting user privacy by providing an opt-out mechanism.

```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4317
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4318
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4319
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4322
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4320
- [ ] https://github.com/bacalhau-project/docs/issues/30
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4354
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4415
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4489
```

### Considerations

1. Ensure all collected data is anonymized and non-PII
2. Design the opt-out mechanism to be user-friendly and easily accessible
3. Comply with relevant data protection regulations
4. Balance the detail of collected data with user privacy concerns

By completing this epic, we aim to create a more robust, user-centric Bacalhau network while maintaining our commitment to user privacy and transparency.

**Comment by wdbaruni** [comment]
@frrist can you please update the tasks here? I understand exporting to S3 is not complete, but I am not sure about the other items and whether there are other pending tasks or not
