### ISSUE TITLE
Enhanced Embedded UI

### ISSUE THREAD

**Issue by wdbaruni** [bacalhau-project/bacalhau#4325]
Our current embedded UI needs improvement to enhance user experience and functionality. We aim to create a new version that is more intuitive, visually appealing, and efficient for our users.

```[tasklist]
### Tasks
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4367
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4368
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4369
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4370
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4371
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4372
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4374
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4375
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4376
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4377
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4378
- [ ] https://github.com/bacalhau-project/bacalhau/issues/4379
```
