### ISSUE TITLE
Install instructions/script for bare metal (ubuntu)

### ISSUE THREAD

**Issue by enricorotundo** [bacalhau-project/bacalhau#620]
ETA: 2023Q1

Originally started from https://github.com/filecoin-project/bacalhau/issues/547, this is about automating the installation fo  Bacalhau on a fresh new machine. 

## Task list for bare metal installation script

- [x] Reuse parts of the [remote_files/scripts](https://github.com/filecoin-project/bacalhau/tree/main/ops/terraform/remote_files/scripts)
- [ ] Add everyone's ssh keys
- [ ] Manage secrets
- [x] Manage env vars
- [x] Install bacalhau and dependencies
- [x] Run `serve` as systemd service
- [ ] Check if node joined the mainnet

## Depdendecies

* `/terraform_node/variables`
* `/terraform_node/nginx.conf`
* `sudo mount /dev/sdb /data`
* services
* `remote_files/configs/unsafe-private-key` ??

**Comment by enricorotundo** [comment]
Related to https://github.com/filecoin-project/bacalhau/issues/607

**Comment by enricorotundo** [comment]
WIP work's here: https://github.com/filecoin-project/bacalhau/tree/620-install-instructionsscript-for-bare-metal-ubuntu/ops/scripted_install
