### ISSUE TITLE
Smart Contract → Consensus

### ISSUE THREAD

**Issue by lukemarsden** [bacalhau-project/bacalhau#660]
Design doc: https://docs.google.com/document/d/1i9Kk2Ml07A9U3ajLSSr6cRlXIC9OWLzoKQlv_XTJ4yM

- [ ] https://github.com/filecoin-project/bacalhau/issues/771 Implement a mock smart contract that can be used by the [simulator](https://github.com/filecoin-project/bacalhau/issues/658).  The mock smart contract should have the functionality required by the localdb and transport interfaces (i.e it should keep track of jobs, bids and emit events)
- [ ] Implement an EVM based (i.e. solidity) smart contract that can be deployed to a local development ethereum node - the smart contract should have the functionality required by the localdb and transport interfaces (i.e it should keep track of jobs, bids and emit events)
- [ ] Implement a “smart contract” implementation of the transport and localdb interfaces that connect to a deployed version of the above smart contract and react to events emitted from that contract in the same way as the current libp2p implementation.
- [ ] Ensure that the test suite passes i.e. we have feature parity.

**Comment by wdbaruni** [comment]
As discussed over slack, I am questioning the need to build our own smart contract simulator. Our use case is not unique and we should be able to reuse existing EVM smart contract simulators out there. 

Also, I don't think we should start implementing a simulator or a smart contract without first disambiguating our blockchain integration, which should define the requirements and scenarios that the simulator should cover. My recommendations are as follows:

1. We first should define our integration options with the blockchain. We can evaluate the tradeoffs between many of these options without having to implement proof of concepts or testing them against simulators. Just purely based on fundamentals. I have already documented most of this in [FVM Integration Options](https://www.notion.so/pl-strflt/FVM-Integration-Options-In-Progress-3f7f40ac0b4d4729bc80ced2cc73b379) doc, which covers the happy path without diving deep into disputes or edge cases. You can decide if this is good enough to unblock the next step and work on the dispute handling design on parallel, or if they should happen in sequence. 
1. Then we define the testing scenarios that will not only help to verify and compare the correctness of the selected option(s), but I am assuming will also help to verify future changes as well. We can only define the testing scenarios after step 1 is complete after we know which options we are seriously considering
1. The testing scenarios will act as a requirement to our testing framework, which might be fulfilled by an existing framework such as [Truffle](https://trufflesuite.com/), or we end up deciding to build our own. At least we will be making an informed decision and minimize the need to re-invent the wheel

**Comment by lukemarsden** [comment]
> Just purely based on fundamentals. [...]

I think we have a difference of approaches here - I've always found prototypes immensely valuable, versus trying to figure out a design in text. Let's discuss this more!

**Comment by wdbaruni** [comment]
Whatever have worked for you before :)

In my case it depends on how ambiguous the problem is. Spending some time in a design for ambiguous problems has been valuable for me as it helps clarify and focus on the big picture, helps be right a lot by making the correct decisions early on, helps cover more edge cases, opens the door for early feedback and design reviews, avoid being biased towards a solution/prototype that I might've already invested it, allows better project estimation and planning, helps in scoping what needs to be prototyped, reduce throw away effort, and lastly the design docs will work as reference for new hires to get up to speed. Prototypes can be helpful as a proof of concept of some design proposals. Obviously we don't want to spend too much time in design and get stuck in analysis paralysis. 

Again, you have spent way more time in this problem than myself and it may not be as ambiguous to you as it is to me. You already have some design docs and you might be in a state where a prototype is needed to clarify the next steps :)

**Comment by lukemarsden** [comment]
Yeah, don't get me wrong, I am a big advocate of writing things down 😁 

In this case, I'm finding co-evolving the design doc with some prototyping is helping me get my teeth into the problem.

And TOTALLY, being biased towards a prototype that one has invested in is a huge risk.

**Comment by wdbaruni** [comment]
We are on the same page then. Looking forward to the prototype and playing with the simulator 😃
